modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
[[mods]]
modId="iguanatweaksreborn"
version="${file.jarVersion}"
displayName="Iguana Tweaks Reborn"
displayURL="https://www.curseforge.com/minecraft/mc-mods/iguanatweaks-reborn"
#logoFile="examplemod.png"
credits = "Thanks to Iguana for the original Mod. Effect Icons made by hamzaa#1200. Injured sound by thecheeseman from freesound.org"
authors = "Insane96MCP"
description = '''
Multiple changes to make Minecraft Harder.
Movement Restrictions, Farming, Mining, Explosions and much more.
'''
# Catalogue icon
itemIcon = "minecraft:golden_hoe"
# Configured background
configBackground = "minecraft:textures/block/cobblestone.png"

[[dependencies.iguanatweaksreborn]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.iguanatweaksreborn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.iguanatweaksreborn]]
    modId="insanelib"
    mandatory=true
    versionRange="[1.7.3,)"
    ordering="NONE"
    side="BOTH"
